// File: src/test/templates/COMPONENT_TEMPLATE.test.tsx
// Test Template (Generated by Task 1 — Pattern Extraction)
// Usage: Copy this template, replace COMPONENT with actual component name,
//        then customize test cases per the patterns documented in /tmp/test-patterns.md

// ──────────────────────────────────────────────────────────────────────────────
// Import Block — Pattern: All tests import from @testing-library/react,
// @testing-library/user-event, react-router-dom MemoryRouter, @tanstack/react-query
// QueryClientProvider, and project providers (AuthProvider, ToastProvider, etc.)
// ──────────────────────────────────────────────────────────────────────────────

import { render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import { AuthProvider } from '@/shared/auth/AuthContext';
import { ToastProvider } from '@/shared/ui/Toast';
import { server } from '@/mocks/server';
import { http, HttpResponse } from 'msw';
import COMPONENT from './COMPONENT';

// ──────────────────────────────────────────────────────────────────────────────
// Pattern: Reusable renderPage() helper function
// - Creates a QueryClient with retry: false (prevents retry delays in tests)
// - Wraps component in MemoryRouter with initial route entry
// - Adds providers in order: QueryClientProvider -> AuthProvider -> ToastProvider
// - Returns the render result for further queries
// ──────────────────────────────────────────────────────────────────────────────

function renderPage() {
  const qc = new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: 0 },
      mutations: { retry: false },
    },
  });
  return render(
    <MemoryRouter initialEntries={['/COMPONENT_ROUTE']}>
      <QueryClientProvider client={qc}>
        <AuthProvider>
          <ToastProvider>
            <COMPONENT />
          </ToastProvider>
        </AuthProvider>
      </QueryClientProvider>
    </MemoryRouter>,
  );
}

// ──────────────────────────────────────────────────────────────────────────────
// Pattern: MSW lifecycle hooks (identical across ALL test files)
// - beforeAll: server.listen({ onUnhandledRequest: 'bypass' })
//   → Intercepts all fetch calls; bypasses any unhandled ones
// - afterEach: server.resetHandlers()
//   → Resets handler overrides from individual tests back to default handlers
// - afterAll: server.close()
//   → Shuts down MSW server completely
// ──────────────────────────────────────────────────────────────────────────────

beforeAll(() => server.listen({ onUnhandledRequest: 'bypass' }));
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

// ──────────────────────────────────────────────────────────────────────────────
// Pattern: describe/it structure
// - describe('ComponentName', () => { ... }) — top-level describe matches component
// - Nested describes for logical groups: 'loading state', 'error state', etc.
// - it() descriptions use full sentences: 'renders heading', 'shows X after Y'
// ──────────────────────────────────────────────────────────────────────────────

describe('COMPONENT', () => {
  // ── Pattern: Static render test (no async, no API wait) ──────────────
  it('renders page heading', () => {
    renderPage();
    expect(screen.getByText('COMPONENT HEADING')).toBeInTheDocument();
  });

  // ── Pattern: Loading/skeleton state test
  // Shows loading state then content after async fetch ────────────────────────
  it('shows skeleton while loading then renders content', async () => {
    // Optional: add slow handler to test loading state
    // server.use(
    //   http.get('*/api/v1/endpoint', async () => {
    //     await new Promise((r) => setTimeout(r, 100));
    //     return HttpResponse.json({ data: [] });
    //   }),
    // );

    renderPage();

    // Wait for content to appear (skeleton disappears on load)
    expect(await screen.findByText('CONTENT')).toBeInTheDocument();
  });

  // ── Pattern: Async content via findBy* (auto-retries until timeout) ──────
  it('shows API-driven content after load', async () => {
    renderPage();
    expect(await screen.findByText('ASYNC_CONTENT')).toBeInTheDocument();
  });

  // ── Pattern: User interaction with userEvent.setup() ────────────────────
  it('handles user interaction and triggers API call', async () => {
    const user = userEvent.setup();
    renderPage();

    await user.click(screen.getByRole('button', { name: /BUTTON_LABEL/i }));

    expect(await screen.findByText('RESULT')).toBeInTheDocument();
  });

  // ── Pattern: Form validation — type into inputs, submit, assert errors ────
  it('shows validation errors for empty fields', async () => {
    const user = userEvent.setup();
    renderPage();

    await user.click(screen.getByRole('button', { name: /SUBMIT/i }));

    expect(await screen.findByText(/REQUIRED/i)).toBeInTheDocument();
  });

  // ── Pattern: Form submission with valid data ────────────────────────────
  it('submits form successfully with valid data', async () => {
    const user = userEvent.setup();
    renderPage();

    await user.type(screen.getByLabelText('FIELD_LABEL'), 'VALUE');
    await user.click(screen.getByRole('button', { name: /SUBMIT/i }));

    await waitFor(() => {
      expect(screen.queryByText('MODAL_OR_FORM')).not.toBeInTheDocument();
    });
  });

  // ── Pattern: Per-test MSW handler override via server.use() ─────────────
  it('shows API error on failed request', async () => {
    server.use(
      http.get('*/api/v1/endpoint', () => {
        return HttpResponse.json(
          { error: { code: 'SYS-500', message: 'Internal server error' } },
          { status: 500 },
        );
      }),
    );

    renderPage();

    await waitFor(() => {
      expect(screen.getByText('PAGE_HEADING')).toBeInTheDocument();
    });
  });

  // ── Pattern: Specific error code response testing ───────────────────────
  it('shows rate limit error (429)', async () => {
    server.use(
      http.post('*/api/v1/auth/login', () => {
        return HttpResponse.json(
          { error: { code: 'RATE-001', message: 'Too many attempts. Try again later.' } },
          { status: 429 },
        );
      }),
    );

    const user = userEvent.setup();
    renderPage();

    await user.click(screen.getByRole('button', { name: /SUBMIT/i }));

    expect(await screen.findByText(/Too many attempts/i)).toBeInTheDocument();
  });

  // ── Pattern: Loading state assertion (button disabled during submit) ──────
  it('shows loading state while submitting', async () => {
    server.use(
      http.post('*/api/v1/auth/login', async () => {
        await new Promise((resolve) => setTimeout(resolve, 500));
        return HttpResponse.json({
          data: {
            access_token: 'test',
            refresh_token: 'test',
            user: {
              id: '1',
              email: 'test@example.com',
              full_name: 'Test',
              property_scopes: [],
              is_active: true,
            },
          },
        });
      }),
    );

    const user = userEvent.setup();
    renderPage();

    await user.click(screen.getByRole('button', { name: /SUBMIT/i }));

    // Button should be disabled during async submission
    expect(screen.getByRole('button', { name: /SUBMIT/i })).toBeDisabled();
  });

  // ── Pattern: Mobile viewport testing ─────────────────────────────────────
  it('renders correctly on narrow screens', async () => {
    vi.spyOn(window, 'innerWidth', 'get').mockReturnValue(375);

    renderPage();

    expect(await screen.findByText('CONTENT')).toBeInTheDocument();

    vi.restoreAllMocks();
  });

  // ── Pattern: Accessibility — tab roles, aria-selected ────────────────────
  it('has proper tab navigation', () => {
    renderPage();

    const tab = screen.getByRole('tab', { name: 'TAB_NAME' });
    expect(tab).toHaveAttribute('aria-selected', 'true');
  });
});
