/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/auth/login": {
    /**
     * Login
     * @description Authenticate user and return JWT tokens (FR-USER-01).
     *
     * Request body
     * ------------
     * .. code-block:: json
     *
     *     {"email": "...", "password": "..."}
     *
     * Responses
     * ---------
     * 200
     *     ``{"data": {"access_token": "...", "refresh_token": "...", "user": {...}}}``
     * 401
     *     ``{"error": {"code": "AUTH-001", "message": "Invalid email or password"}}``
     * 403
     *     ``{"error": {"code": "AUTH-002", "message": "Account is not active"}}``
     */
    post: operations["login_api_v1_auth_login_post"];
  };
  "/api/v1/auth/register": {
    /**
     * Register
     * @description Accept an invitation and create a new user account (FR-USER-02).
     *
     * Request body
     * ------------
     * .. code-block:: json
     *
     *     {"invite_token": "...", "full_name": "...", "password": "...", "phone": "..."}
     *
     * Responses
     * ---------
     * 201
     *     ``{"data": {"id": "...", "email": "...", "full_name": "...", "property_scopes": [], "is_active": true}}``
     * 400
     *     ``{"error": {"code": "VAL-400", "message": "..."}}`` (validation error)
     * 409
     *     ``{"error": {"code": "AUTH-004", "message": "Email already in use"}}``
     */
    post: operations["register_api_v1_auth_register_post"];
  };
  "/api/v1/auth/invite": {
    /**
     * Invite
     * @description Send an invitation link to a new user (FR-USER-02).
     *
     * Requires the current user to have sufficient property scope
     * (validated in the service layer).
     *
     * Request body
     * ------------
     * .. code-block:: json
     *
     *     {"email": "...", "property_id": "..."}
     *
     * Responses
     * ---------
     * 201
     *     ``{"data": {"invite_link": "..."}}``
     * 403
     *     ``{"error": {"code": "AUTH-005", "message": "Insufficient property scope"}}``
     * 409
     *     ``{"error": {"code": "AUTH-004", "message": "Email already in use"}}``
     */
    post: operations["invite_api_v1_auth_invite_post"];
  };
  "/api/v1/auth/refresh": {
    /**
     * Refresh
     * @description Issue a new access token from a valid refresh token (FR-USER-03).
     *
     * Request body
     * ------------
     * .. code-block:: json
     *
     *     {"refresh_token": "..."}
     *
     * Responses
     * ---------
     * 200
     *     ``{"data": {"access_token": "..."}}``
     * 401
     *     ``{"error": {"code": "AUTH-007", "message": "Invalid or expired refresh token"}}``
     */
    post: operations["refresh_api_v1_auth_refresh_post"];
  };
  "/api/v1/auth/me": {
    /**
     * Get Me
     * @description Return the authenticated user's profile (FR-USER-01).
     *
     * Requires a valid Bearer token in the ``Authorization`` header.
     *
     * Responses
     * ---------
     * 200
     *     ``{"data": {"id": "...", "email": "...", "full_name": "...", "property_scopes": [], "is_active": true}}``
     * 401
     *     ``{"error": {"code": "AUTH-009", "message": "Invalid or expired access token"}}``
     */
    get: operations["get_me_api_v1_auth_me_get"];
  };
  "/api/v1/meter-readings": {
    /**
     * Record a meter reading (FR-METER-01, BR-07)
     * @description Record a new electric/water meter reading for a room.
     *
     * Enforces BR-07: current meter values must be >= previous values.
     */
    post: operations["create_meter_reading_api_v1_meter_readings_post"];
  };
  "/api/v1/meter-readings/{room_id}/history": {
    /**
     * Get meter reading history (FR-METER-02)
     * @description Get paginated meter reading history for a room.
     */
    get: operations["get_meter_history_api_v1_meter_readings__room_id__history_get"];
  };
  "/api/v1/invoices/generate": {
    /**
     * Generate a monthly invoice (FR-METER-06, BR-12)
     * @description Generate a monthly invoice with rent, utilities, and common fee.
     *
     * Enforces BR-10 (utility rate cascade) and BR-12 (calculation).
     */
    post: operations["generate_invoice_api_v1_invoices_generate_post"];
  };
  "/api/v1/invoices/{id}": {
    /**
     * Get invoice with line items (FR-METER-10)
     * @description Retrieve an invoice with its line items.
     */
    get: operations["get_invoice_api_v1_invoices__id__get"];
  };
  "/api/v1/payments": {
    /**
     * Record a payment (FR-METER-09)
     * @description Record a payment against an invoice.
     *
     * Updates invoice paid amount and triggers status change if fully paid.
     */
    post: operations["record_payment_api_v1_payments_post"];
  };
  "/api/v1/properties/{property_id}": {
    /**
     * Get property by ID (FR-PROP-02)
     * @description Retrieve a single property by its UUID.
     *
     * Returns 404 if the property does not exist.
     */
    get: operations["get_property_api_v1_properties__property_id__get"];
  };
  "/api/v1/properties": {
    /**
     * List all properties
     * @description GET /api/v1/properties — list all properties.
     */
    get: operations["list_properties_api_v1_properties_get"];
    /**
     * Create a new property (FR-PROP-01)
     * @description Create a new property.
     *
     * The caller becomes the owner of the property.
     * Audit log is recorded automatically by the service.
     */
    post: operations["create_property_api_v1_properties_post"];
  };
  "/api/v1/properties/{property_id}/rooms": {
    /**
     * Get property with all its rooms (FR-PROP-06)
     * @description Retrieve a property with its full room list.
     */
    get: operations["get_property_rooms_api_v1_properties__property_id__rooms_get"];
  };
  "/api/v1/rooms/{room_id}/status": {
    /**
     * Update room status (FR-PROP-05)
     * @description Update a room's current status (available/occupied/maintenance).
     *
     * Audit log is recorded automatically by the service.
     */
    patch: operations["update_room_status_api_v1_rooms__room_id__status_patch"];
  };
  "/api/v1/tenants": {
    /**
     * Create a new tenant (FR-TENANT-01, FR-TENANT-02)
     * @description Register a new tenant with encrypted ID card.
     *
     * The ID card number is encrypted with Fernet before storage
     * and is **never** returned in the response.
     * Audit log is recorded automatically.
     */
    post: operations["create_tenant_api_v1_tenants_post"];
  };
  "/api/v1/tenants/search": {
    /**
     * Search tenants (FR-TENANT-04)
     * @description Search for tenants by name, phone, or email within a property.
     *
     * Response follows SDD §3.1 pagination format:
     * ``{"data": [...], "meta": {"page", "limit", "total", "has_next"}}``
     */
    get: operations["search_tenants_api_v1_tenants_search_get"];
  };
  "/api/v1/contracts": {
    /**
     * Create a new rental contract
     * @description Creates an active contract for a room+tenant.  Enforces BR-01 (one active per room) and BR-02 (min deposit).
     */
    post: operations["create_contract_api_v1_contracts_post"];
  };
  "/api/v1/contracts/active": {
    /**
     * List active contracts
     * @description Returns all active contracts, optionally filtered by property_id.
     */
    get: operations["list_active_contracts_api_v1_contracts_active_get"];
  };
  "/api/v1/contracts/{contract_id}": {
    /**
     * Get a contract by ID
     * @description Returns full contract details including termination and extensions.
     */
    get: operations["get_contract_api_v1_contracts__contract_id__get"];
  };
  "/api/v1/contracts/{contract_id}/terminate": {
    /**
     * Terminate an active contract
     * @description Terminates an active contract (BR-04).  Requires reason.  Sets room to available.
     */
    patch: operations["terminate_contract_api_v1_contracts__contract_id__terminate_patch"];
  };
  "/api/v1/contracts/{contract_id}/extend": {
    /**
     * Extend a contract's lease
     * @description Extends the end date of an active contract and records the extension.
     */
    post: operations["extend_lease_api_v1_contracts__contract_id__extend_post"];
  };
  "/api/v1/contracts/{contract_id}/renew": {
    /**
     * Renew a terminated/expired contract
     * @description Creates a new contract from a terminated/expired original.  Same room/tenant, updated terms.
     */
    post: operations["renew_contract_api_v1_contracts__contract_id__renew_post"];
  };
  "/api/v1/leases/{room_id}/history": {
    /**
     * Get lease history for a room
     * @description Returns all contracts (past and present) for a given room, newest first.
     */
    get: operations["get_lease_history_api_v1_leases__room_id__history_get"];
  };
  "/api/v1/maintenance-requests": {
    /**
     * Create a maintenance request
     * @description POST /api/v1/maintenance-requests — SDD §3.3.
     */
    post: operations["create_maintenance_request_api_v1_maintenance_requests_post"];
  };
  "/api/v1/maintenance-requests/pending": {
    /**
     * List pending maintenance requests by property
     * @description GET /api/v1/maintenance-requests/pending — SDD §3.3.
     */
    get: operations["list_pending_requests_api_v1_maintenance_requests_pending_get"];
  };
  "/api/v1/maintenance-requests/{request_id}": {
    /**
     * Get a maintenance request by ID
     * @description GET /api/v1/maintenance-requests/{id} — SDD §3.3.
     */
    get: operations["get_maintenance_request_api_v1_maintenance_requests__request_id__get"];
  };
  "/api/v1/maintenance-requests/{request_id}/status": {
    /**
     * Update maintenance request status
     * @description Updates status per BR-09 workflow: pending → in_progress → resolved/cancelled.
     */
    patch: operations["update_maintenance_status_api_v1_maintenance_requests__request_id__status_patch"];
  };
  "/api/v1/maintenance-requests/{request_id}/assign": {
    /**
     * Assign a maintenance request to a user
     * @description PATCH /api/v1/maintenance-requests/{id}/assign.
     */
    patch: operations["assign_maintenance_request_api_v1_maintenance_requests__request_id__assign_patch"];
  };
  "/api/v1/dashboard/summary": {
    /**
     * Get dashboard summary
     * @description Returns occupancy, revenue, overdue, and maintenance counts for a property.
     */
    get: operations["get_dashboard_summary_api_v1_dashboard_summary_get"];
  };
  "/api/v1/dashboard/revenue": {
    /**
     * Get revenue report
     * @description Monthly revenue aggregation for a date range.
     */
    get: operations["get_revenue_report_api_v1_dashboard_revenue_get"];
  };
  "/api/v1/dashboard/occupancy": {
    /**
     * Get occupancy snapshot
     * @description Returns current occupancy rate and room counts.
     */
    get: operations["get_occupancy_api_v1_dashboard_occupancy_get"];
  };
  "/api/v1/notifications/test": {
    /**
     * Send a test notification
     * @description Creates and sends a test notification (mock). Fail-silent — always returns 201.
     */
    post: operations["send_test_notification_api_v1_notifications_test_post"];
  };
  "/api/v1/notifications/history": {
    /**
     * Get notification history
     * @description GET /api/v1/notifications/history.
     */
    get: operations["get_notification_history_api_v1_notifications_history_get"];
  };
  "/api/v1/notifications/{notif_id}/resend": {
    /**
     * Resend a failed notification
     * @description PATCH /api/v1/notifications/{id}/resend.
     */
    patch: operations["resend_notification_api_v1_notifications__notif_id__resend_patch"];
  };
  "/api/v1/admin/audit-logs": {
    /**
     * View audit logs (paginated)
     * @description Returns paginated audit logs for a property. Owner role required.
     */
    get: operations["get_audit_logs_api_v1_admin_audit_logs_get"];
  };
  "/api/v1/admin/config": {
    /**
     * View system configuration
     * @description Returns system settings with secrets masked. Owner role required.
     */
    get: operations["get_system_config_api_v1_admin_config_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AssignMaintenanceRequest
     * @description Request body for PATCH /api/v1/maintenance-requests/{id}/assign.
     */
    AssignMaintenanceRequest: {
      /**
       * Assigned To
       * Format: uuid
       */
      assigned_to: string;
    };
    /** AuditLogListResponse */
    AuditLogListResponse: {
      /** Data */
      data: components["schemas"]["AuditLogResponse"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /** AuditLogResponse */
    AuditLogResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** User Id */
      user_id?: string | null;
      /** Action */
      action: string;
      /** Resource Type */
      resource_type: string;
      /** Resource Id */
      resource_id?: string | null;
      /** Property Id */
      property_id?: string | null;
      /** Metadata */
      metadata?: unknown;
      /** Ip Address */
      ip_address?: string | null;
      /**
       * Timestamp
       * Format: date-time
       */
      timestamp: string;
    };
    /**
     * AuthRequest
     * @description Payload for ``POST /api/v1/auth/login`` (SDD §3.3).
     *
     * Validates that the password meets minimum length and complexity
     * requirements before reaching the service layer.
     */
    AuthRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /**
     * ContractCreateResponse
     * @description Wrapper for 201 CREATED response (SDD §3.1).
     */
    ContractCreateResponse: {
      data: components["schemas"]["ContractResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * ContractListResponse
     * @description Paginated list response for contracts (SDD §3.1).
     */
    ContractListResponse: {
      /** Data */
      data: components["schemas"]["ContractResponse"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * ContractResponse
     * @description Response body for a single Contract resource (SDD §3.1 format).
     */
    ContractResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /** Monthly Rent */
      monthly_rent: string;
      /** Deposit Amount */
      deposit_amount: string;
      status: components["schemas"]["ContractStatus"];
      /** Special Conditions */
      special_conditions?: string | null;
      /**
       * Is Renewal
       * @default false
       */
      is_renewal?: boolean;
      /** Renewed From Id */
      renewed_from_id?: string | null;
      /** Created By */
      created_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      termination?: components["schemas"]["ContractTerminationResponse"] | null;
      /**
       * Extensions
       * @default []
       */
      extensions?: components["schemas"]["LeaseExtensionResponse"][];
    };
    /**
     * ContractStatus
     * @description Possible states for a Contract (SDD §6.2: State Machines).
     *
     * Transitions:
     *     draft ──→ active (via signing)
     *     active ──→ terminated (via terminate_contract, BR-04)
     *     active ──→ expired (auto via scheduler when end_date < today)
     *     terminated ──→ (immutable, new contract created for renew)
     *     expired ──→ (immutable)
     * @enum {string}
     */
    ContractStatus: "active" | "terminated" | "expired" | "draft";
    /**
     * ContractTerminationResponse
     * @description Termination record embedded in ContractResponse (SDD §5.2).
     */
    ContractTerminationResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Reason */
      reason: string;
      /**
       * Termination Date
       * Format: date
       */
      termination_date: string;
      /** Notes */
      notes?: string | null;
      /** Terminated By */
      terminated_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * CreateContractRequest
     * @description Request body for POST /api/v1/contracts (SDD §3.3).
     *
     * Validation:
     *     - ``end_date`` must be after ``start_date``.
     *     - ``monthly_rent`` must be positive.
     *     - ``deposit_amount`` must be >= 0.
     *     - ``start_date`` must not be in the past (service layer also checks).
     *     - BR-01/BR-02 enforced in service layer (not here).
     */
    CreateContractRequest: {
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /** Monthly Rent */
      monthly_rent: number | string;
      /** Deposit Amount */
      deposit_amount: number | string;
      /** Special Conditions */
      special_conditions?: string | null;
    };
    /**
     * CreateMaintenanceRequest
     * @description Request body for POST /api/v1/maintenance-requests.
     *
     * Validation:
     *     - ``title``: min 3 characters.
     *     - ``description``: min 10 characters.
     *     - ``priority``: must be a valid Priority enum value.
     *     - ``room_id``: must be a valid UUID.
     *     - ``images``: max 5 (future).
     */
    CreateMaintenanceRequest: {
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** @default medium */
      priority?: components["schemas"]["Priority"];
    };
    /**
     * CreateMeterReadingRequest
     * @description Request body for POST /api/v1/meter-readings.
     *
     * Validation:
     *     - BR-07: electric_current >= electric_previous, water_current >= water_previous
     *     - billing_month: 1-12, billing_year: >= 2020
     */
    CreateMeterReadingRequest: {
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /** Billing Month */
      billing_month: number;
      /** Billing Year */
      billing_year: number;
      /**
       * Electric Previous
       * @default 0
       */
      electric_previous?: number | string;
      /** Electric Current */
      electric_current: number | string;
      /**
       * Water Previous
       * @default 0
       */
      water_previous?: number | string;
      /** Water Current */
      water_current: number | string;
    };
    /**
     * CreatePropertyRequest
     * @description Request body for POST /api/v1/properties.
     *
     * Validation:
     *     - ``billing_due_day`` must be 1-28.
     *     - ``min_deposit_months`` >= 1.
     *     - ``name`` must not be empty.
     */
    CreatePropertyRequest: {
      /** Name */
      name: string;
      /** Address */
      address: string;
      /** Billing Due Day */
      billing_due_day: number;
      /**
       * Min Deposit Months
       * @default 2
       */
      min_deposit_months?: number;
    };
    /**
     * CreateTenantRequest
     * @description Request body for POST /api/v1/tenants.
     *
     * Validation:
     *     - ``phone`` must be a valid Thai phone number (10 digits, starts with 0).
     *     - ``id_card_number`` must be 13 digits (Thai national ID format).
     *     - ``email`` is optional but must be valid if provided.
     */
    CreateTenantRequest: {
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Full Name */
      full_name: string;
      /** Id Card Number */
      id_card_number: string;
      /** Phone */
      phone: string;
      /** Email */
      email?: string | null;
      /** Emergency Contact Name */
      emergency_contact_name?: string | null;
      /** Emergency Contact Phone */
      emergency_contact_phone?: string | null;
    };
    /**
     * DashboardSummaryResponse
     * @description Response for GET /api/v1/dashboard/summary.
     */
    DashboardSummaryResponse: {
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Total Rooms */
      total_rooms: number;
      /** Occupied Rooms */
      occupied_rooms: number;
      /** Occupancy Rate */
      occupancy_rate: number;
      /** Monthly Revenue */
      monthly_revenue: string;
      /** Overdue Count */
      overdue_count: number;
      /** Overdue Amount */
      overdue_amount: string;
      /** Pending Maintenance */
      pending_maintenance: number;
      /** Active Contracts */
      active_contracts: number;
    };
    /**
     * DashboardSummaryWrapper
     * @description Wrapper for the summary endpoint.
     */
    DashboardSummaryWrapper: {
      data: components["schemas"]["DashboardSummaryResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * ExtendLeaseRequest
     * @description Request body for POST /api/v1/contracts/{id}/extend.
     *
     * Validation:
     *     - ``new_end_date`` must be after the current end_date.
     */
    ExtendLeaseRequest: {
      /**
       * New End Date
       * Format: date
       */
      new_end_date: string;
      /** Reason */
      reason?: string | null;
    };
    /**
     * GenerateInvoiceRequest
     * @description Request body for POST /api/v1/invoices/generate.
     *
     * Validation:
     *     - billing_month: 1-12, billing_year >= 2020
     */
    GenerateInvoiceRequest: {
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Billing Month */
      billing_month: number;
      /** Billing Year */
      billing_year: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * InviteRequest
     * @description Payload for ``POST /api/v1/auth/invite`` (SDD §3.3).
     *
     * An admin sends an invitation for a specific email address and property.
     *
     * .. note::
     *    Not strict so that string-encoded UUIDs from JSON deserialisation
     *    are automatically coerced to ``uuid.UUID``.
     */
    InviteRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
    };
    /**
     * InvoiceCreateResponse
     * @description 201 CREATED wrapper for invoice generation.
     */
    InvoiceCreateResponse: {
      data: components["schemas"]["InvoiceResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * InvoiceDetailResponse
     * @description Response for GET /api/v1/invoices/{id} — includes line items.
     */
    InvoiceDetailResponse: {
      invoice: components["schemas"]["InvoiceResponse"];
      /** Line Items */
      line_items: components["schemas"]["InvoiceLineItemResponse"][];
    };
    /**
     * InvoiceLineItemResponse
     * @description Response body for a single InvoiceLineItem.
     */
    InvoiceLineItemResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Invoice Id
       * Format: uuid
       */
      invoice_id: string;
      /** Line Type */
      line_type: string;
      /** Description */
      description: string;
      /** Quantity */
      quantity: string;
      /** Unit Price */
      unit_price: string;
      /** Amount */
      amount: string;
    };
    /**
     * InvoiceResponse
     * @description Response body for a single Invoice resource.
     */
    InvoiceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Invoice Number */
      invoice_number: string;
      /**
       * Contract Id
       * Format: uuid
       */
      contract_id: string;
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Billing Month */
      billing_month: number;
      /** Billing Year */
      billing_year: number;
      /**
       * Due Date
       * Format: date
       */
      due_date: string;
      /** Status */
      status: string;
      /** Total Amount */
      total_amount: string;
      /** Paid Amount */
      paid_amount: string;
      /** Notes */
      notes?: string | null;
      /** Created At */
      created_at?: string | null;
    };
    /**
     * LeaseExtensionResponse
     * @description Lease extension record embedded in ContractResponse.
     */
    LeaseExtensionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Previous End Date
       * Format: date
       */
      previous_end_date: string;
      /**
       * Extended To
       * Format: date
       */
      extended_to: string;
      /** Reason */
      reason?: string | null;
      /** Extended By */
      extended_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * LeaseHistoryItem
     * @description A single lease history entry for a room.
     */
    LeaseHistoryItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Tenant Id
       * Format: uuid
       */
      tenant_id: string;
      /**
       * Start Date
       * Format: date
       */
      start_date: string;
      /**
       * End Date
       * Format: date
       */
      end_date: string;
      /** Monthly Rent */
      monthly_rent: string;
      status: components["schemas"]["ContractStatus"];
      /** Is Renewal */
      is_renewal: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Termination Reason */
      termination_reason?: string | null;
      /** Termination Date */
      termination_date?: string | null;
    };
    /**
     * LeaseHistoryResponse
     * @description Response for GET /api/v1/leases/{room_id}/history.
     */
    LeaseHistoryResponse: {
      /** Data */
      data: components["schemas"]["LeaseHistoryItem"][];
      /** Meta */
      meta?: null;
    };
    /**
     * MaintenanceCreateResponse
     * @description Wrapper for 201 CREATED response (SDD §3.1).
     */
    MaintenanceCreateResponse: {
      data: components["schemas"]["MaintenanceResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * MaintenanceListResponse
     * @description List wrapper for maintenance requests (SDD §3.1).
     */
    MaintenanceListResponse: {
      /** Data */
      data: components["schemas"]["MaintenanceResponse"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * MaintenanceResponse
     * @description Response body for a single MaintenanceRequest resource (SDD §3.1).
     */
    MaintenanceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      priority: components["schemas"]["Priority"];
      status: components["schemas"]["MaintenanceStatus"];
      /** Assigned To */
      assigned_to?: string | null;
      /** Created By */
      created_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MaintenanceStatus
     * @description Possible states for a MaintenanceRequest (BR-09 workflow).
     *
     * Valid transitions:
     *     pending ──→ in_progress
     *     in_progress ──→ resolved
     *     in_progress ──→ cancelled
     *     pending ──→ cancelled
     * @enum {string}
     */
    MaintenanceStatus: "pending" | "in_progress" | "resolved" | "cancelled";
    /**
     * MeterHistoryResponse
     * @description Paginated response for meter reading history.
     */
    MeterHistoryResponse: {
      /** Data */
      data: components["schemas"]["MeterReadingResponse"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * MeterReadingCreateResponse
     * @description 201 CREATED wrapper for meter readings.
     */
    MeterReadingCreateResponse: {
      data: components["schemas"]["MeterReadingResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * MeterReadingResponse
     * @description Response body for a single MeterReading resource.
     */
    MeterReadingResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Room Id
       * Format: uuid
       */
      room_id: string;
      /** Billing Month */
      billing_month: number;
      /** Billing Year */
      billing_year: number;
      /** Electric Previous */
      electric_previous: string;
      /** Electric Current */
      electric_current: string;
      /** Electric Used */
      electric_used: string;
      /** Water Previous */
      water_previous: string;
      /** Water Current */
      water_current: string;
      /** Water Used */
      water_used: string;
      /**
       * Read Date
       * Format: date
       */
      read_date: string;
    };
    /**
     * NotificationChannel
     * @enum {string}
     */
    NotificationChannel: "email" | "line" | "sms";
    /** NotificationCreateResponse */
    NotificationCreateResponse: {
      data: components["schemas"]["NotificationResponse"];
      /** Meta */
      meta?: null;
    };
    /** NotificationListResponse */
    NotificationListResponse: {
      /** Data */
      data: components["schemas"]["NotificationResponse"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /** NotificationResponse */
    NotificationResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** User Id */
      user_id?: string | null;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Channel */
      channel: string;
      /** Subject */
      subject: string;
      /** Body */
      body: string;
      /** Status */
      status: string;
      /** Error Message */
      error_message?: string | null;
      /** Created By */
      created_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Sent At */
      sent_at?: string | null;
    };
    /**
     * OccupancyResponse
     * @description Response for GET /api/v1/dashboard/occupancy.
     */
    OccupancyResponse: {
      /** Data */
      data: {
        [key: string]: unknown;
      };
      /** Meta */
      meta?: null;
    };
    /**
     * PaymentCreateResponse
     * @description 201 CREATED wrapper for payment recording.
     */
    PaymentCreateResponse: {
      data: components["schemas"]["PaymentResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * PaymentMethod
     * @description Payment methods accepted by the system.
     * @enum {string}
     */
    PaymentMethod: "bank_transfer" | "cash" | "promptpay" | "qr_code" | "credit_card";
    /**
     * PaymentResponse
     * @description Response body for a single Payment resource.
     */
    PaymentResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Invoice Id
       * Format: uuid
       */
      invoice_id: string;
      /** Amount */
      amount: string;
      /**
       * Payment Date
       * Format: date
       */
      payment_date: string;
      /** Method */
      method: string;
      /** Reference Number */
      reference_number?: string | null;
      /** Slip Image Url */
      slip_image_url?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * Priority
     * @description Priority level for a maintenance request.
     * @enum {string}
     */
    Priority: "low" | "medium" | "high" | "urgent";
    /**
     * PropertyCreateResponse
     * @description Wrapper for 201 CREATED response (SDD §3.1).
     */
    PropertyCreateResponse: {
      data: components["schemas"]["PropertyResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * PropertyListResponse
     * @description Response for GET /api/v1/properties — list all properties.
     */
    PropertyListResponse: {
      /** Data */
      data: components["schemas"]["PropertyResponse"][];
      /** Meta */
      meta?: null;
    };
    /**
     * PropertyResponse
     * @description Response body for a single Property resource (SDD §3.1 format).
     */
    PropertyResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Address */
      address: string;
      /** Billing Due Day */
      billing_due_day: number;
      /** Min Deposit Months */
      min_deposit_months: number;
      /** Created By */
      created_by?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PropertyWithRoomsResponse
     * @description Response for GET /api/v1/properties/{id}/rooms.
     */
    PropertyWithRoomsResponse: {
      property: components["schemas"]["PropertyResponse"];
      /** Rooms */
      rooms: components["schemas"]["RoomResponse"][];
    };
    /**
     * RecordPaymentRequest
     * @description Request body for POST /api/v1/payments.
     *
     * Validation:
     *     - amount > 0
     *     - method must be a valid PaymentMethod enum value
     */
    RecordPaymentRequest: {
      /**
       * Invoice Id
       * Format: uuid
       */
      invoice_id: string;
      /** Amount */
      amount: number | string;
      method: components["schemas"]["PaymentMethod"];
      /** Reference Number */
      reference_number?: string | null;
      /** Slip Image Url */
      slip_image_url?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * RegisterRequest
     * @description Payload for ``POST /api/v1/auth/register`` (SDD §3.3).
     *
     * Carries the invite token alongside the new user's profile data.
     */
    RegisterRequest: {
      /** Invite Token */
      invite_token: string;
      /** Full Name */
      full_name: string;
      /** Password */
      password: string;
      /** Phone */
      phone: string;
    };
    /**
     * RenewContractRequest
     * @description Request body for POST /api/v1/contracts/{id}/renew.
     *
     * Creates a new contract record based on the original.  The original
     * contract must be in ``terminated`` or ``expired`` state (CONT-005).
     */
    RenewContractRequest: {
      /**
       * New Start Date
       * Format: date
       */
      new_start_date: string;
      /**
       * New End Date
       * Format: date
       */
      new_end_date: string;
      /** New Monthly Rent */
      new_monthly_rent: number | string;
      /** New Deposit Amount */
      new_deposit_amount: number | string;
    };
    /**
     * RevenueMetric
     * @description Single revenue data point for a period.
     */
    RevenueMetric: {
      /** Period */
      period: string;
      /** Collected */
      collected: string;
      /** Outstanding */
      outstanding: string;
      /** Total Billed */
      total_billed: string;
    };
    /**
     * RevenueReportResponse
     * @description Response for GET /api/v1/dashboard/revenue.
     */
    RevenueReportResponse: {
      /** Data */
      data: components["schemas"]["RevenueMetric"][];
      /** Meta */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * RoomResponse
     * @description Response body for a single Room resource (SDD §3.1 format).
     *
     * Note: ``images`` is omitted from the response if ``None``.
     */
    RoomResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /**
       * Building Id
       * Format: uuid
       */
      building_id: string;
      /** Floor Id */
      floor_id?: string | null;
      /** Room Number */
      room_number: string;
      /** Room Type */
      room_type: string;
      /** Base Rent */
      base_rent: string;
      /** Status */
      status: string;
      /** Images */
      images?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * RoomStatus
     * @description Possible states for a room (SDD §6: State Machines).
     * @enum {string}
     */
    RoomStatus: "available" | "occupied" | "maintenance";
    /** SendNotificationRequest */
    SendNotificationRequest: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** @default email */
      channel?: components["schemas"]["NotificationChannel"];
      /** Subject */
      subject: string;
      /** Body */
      body: string;
    };
    /** SystemConfigListResponse */
    SystemConfigListResponse: {
      /** Data */
      data: components["schemas"]["SystemConfigResponse"][];
      /** Meta */
      meta?: null;
    };
    /** SystemConfigResponse */
    SystemConfigResponse: {
      /** Key */
      key: string;
      /** Value */
      value: string;
      /**
       * Masked
       * @default false
       */
      masked?: boolean;
    };
    /**
     * TenantCreateResponse
     * @description Wrapper for 201 CREATED response (SDD §3.1).
     */
    TenantCreateResponse: {
      data: components["schemas"]["TenantResponse"];
      /** Meta */
      meta?: null;
    };
    /**
     * TenantResponse
     * @description Response body for a single Tenant resource (SDD §3.1 format).
     *
     * **Security:** ``id_card_number_encrypted`` is deliberately omitted.
     * Sensitive personal data is never returned through the API.
     */
    TenantResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Property Id
       * Format: uuid
       */
      property_id: string;
      /** Full Name */
      full_name: string;
      /** Phone */
      phone: string;
      /** Email */
      email?: string | null;
      /** Emergency Contact Name */
      emergency_contact_name?: string | null;
      /** Emergency Contact Phone */
      emergency_contact_phone?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * TerminateContractRequest
     * @description Request body for POST /api/v1/contracts/{id}/terminate (SDD §3.3).
     *
     * Validation:
     *     - ``reason`` is required and must be non-empty.
     *     - ``termination_date`` defaults to today if not provided.
     */
    TerminateContractRequest: {
      reason: components["schemas"]["TerminationReason"];
      /** Termination Date */
      termination_date?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * TerminationReason
     * @description Standardised reasons for contract termination (SDD §5.2).
     * @enum {string}
     */
    TerminationReason: "tenant_moved_out" | "owner_terminated" | "breach_of_contract" | "mutual_agreement" | "other";
    /**
     * UpdateMaintenanceStatusRequest
     * @description Request body for PATCH /api/v1/maintenance-requests/{id}/status.
     *
     * Validation:
     *     - ``status``: must be a valid MaintenanceStatus enum value.
     *     - BR-09 enforced in service layer.
     */
    UpdateMaintenanceStatusRequest: {
      status: components["schemas"]["MaintenanceStatus"];
    };
    /**
     * UpdateRoomStatusRequest
     * @description Request body for PATCH /api/v1/rooms/{id}/status.
     */
    UpdateRoomStatusRequest: {
      status: components["schemas"]["RoomStatus"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Login
   * @description Authenticate user and return JWT tokens (FR-USER-01).
   *
   * Request body
   * ------------
   * .. code-block:: json
   *
   *     {"email": "...", "password": "..."}
   *
   * Responses
   * ---------
   * 200
   *     ``{"data": {"access_token": "...", "refresh_token": "...", "user": {...}}}``
   * 401
   *     ``{"error": {"code": "AUTH-001", "message": "Invalid email or password"}}``
   * 403
   *     ``{"error": {"code": "AUTH-002", "message": "Account is not active"}}``
   */
  login_api_v1_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Register
   * @description Accept an invitation and create a new user account (FR-USER-02).
   *
   * Request body
   * ------------
   * .. code-block:: json
   *
   *     {"invite_token": "...", "full_name": "...", "password": "...", "phone": "..."}
   *
   * Responses
   * ---------
   * 201
   *     ``{"data": {"id": "...", "email": "...", "full_name": "...", "property_scopes": [], "is_active": true}}``
   * 400
   *     ``{"error": {"code": "VAL-400", "message": "..."}}`` (validation error)
   * 409
   *     ``{"error": {"code": "AUTH-004", "message": "Email already in use"}}``
   */
  register_api_v1_auth_register_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Invite
   * @description Send an invitation link to a new user (FR-USER-02).
   *
   * Requires the current user to have sufficient property scope
   * (validated in the service layer).
   *
   * Request body
   * ------------
   * .. code-block:: json
   *
   *     {"email": "...", "property_id": "..."}
   *
   * Responses
   * ---------
   * 201
   *     ``{"data": {"invite_link": "..."}}``
   * 403
   *     ``{"error": {"code": "AUTH-005", "message": "Insufficient property scope"}}``
   * 409
   *     ``{"error": {"code": "AUTH-004", "message": "Email already in use"}}``
   */
  invite_api_v1_auth_invite_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Refresh
   * @description Issue a new access token from a valid refresh token (FR-USER-03).
   *
   * Request body
   * ------------
   * .. code-block:: json
   *
   *     {"refresh_token": "..."}
   *
   * Responses
   * ---------
   * 200
   *     ``{"data": {"access_token": "..."}}``
   * 401
   *     ``{"error": {"code": "AUTH-007", "message": "Invalid or expired refresh token"}}``
   */
  refresh_api_v1_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Me
   * @description Return the authenticated user's profile (FR-USER-01).
   *
   * Requires a valid Bearer token in the ``Authorization`` header.
   *
   * Responses
   * ---------
   * 200
   *     ``{"data": {"id": "...", "email": "...", "full_name": "...", "property_scopes": [], "is_active": true}}``
   * 401
   *     ``{"error": {"code": "AUTH-009", "message": "Invalid or expired access token"}}``
   */
  get_me_api_v1_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Record a meter reading (FR-METER-01, BR-07)
   * @description Record a new electric/water meter reading for a room.
   *
   * Enforces BR-07: current meter values must be >= previous values.
   */
  create_meter_reading_api_v1_meter_readings_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMeterReadingRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MeterReadingCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get meter reading history (FR-METER-02)
   * @description Get paginated meter reading history for a room.
   */
  get_meter_history_api_v1_meter_readings__room_id__history_get: {
    parameters: {
      query?: {
        start_month?: number | null;
        start_year?: number | null;
        end_month?: number | null;
        end_year?: number | null;
        page?: number;
        limit?: number;
      };
      path: {
        /** @description Room UUID */
        room_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MeterHistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Generate a monthly invoice (FR-METER-06, BR-12)
   * @description Generate a monthly invoice with rent, utilities, and common fee.
   *
   * Enforces BR-10 (utility rate cascade) and BR-12 (calculation).
   */
  generate_invoice_api_v1_invoices_generate_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateInvoiceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["InvoiceCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get invoice with line items (FR-METER-10)
   * @description Retrieve an invoice with its line items.
   */
  get_invoice_api_v1_invoices__id__get: {
    parameters: {
      path: {
        /** @description Invoice UUID */
        id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["InvoiceDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Record a payment (FR-METER-09)
   * @description Record a payment against an invoice.
   *
   * Updates invoice paid amount and triggers status change if fully paid.
   */
  record_payment_api_v1_payments_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordPaymentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PaymentCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get property by ID (FR-PROP-02)
   * @description Retrieve a single property by its UUID.
   *
   * Returns 404 if the property does not exist.
   */
  get_property_api_v1_properties__property_id__get: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List all properties
   * @description GET /api/v1/properties — list all properties.
   */
  list_properties_api_v1_properties_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyListResponse"];
        };
      };
    };
  };
  /**
   * Create a new property (FR-PROP-01)
   * @description Create a new property.
   *
   * The caller becomes the owner of the property.
   * Audit log is recorded automatically by the service.
   */
  create_property_api_v1_properties_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePropertyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PropertyCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get property with all its rooms (FR-PROP-06)
   * @description Retrieve a property with its full room list.
   */
  get_property_rooms_api_v1_properties__property_id__rooms_get: {
    parameters: {
      path: {
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PropertyWithRoomsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update room status (FR-PROP-05)
   * @description Update a room's current status (available/occupied/maintenance).
   *
   * Audit log is recorded automatically by the service.
   */
  update_room_status_api_v1_rooms__room_id__status_patch: {
    parameters: {
      path: {
        room_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateRoomStatusRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create a new tenant (FR-TENANT-01, FR-TENANT-02)
   * @description Register a new tenant with encrypted ID card.
   *
   * The ID card number is encrypted with Fernet before storage
   * and is **never** returned in the response.
   * Audit log is recorded automatically.
   */
  create_tenant_api_v1_tenants_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTenantRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["TenantCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Search tenants (FR-TENANT-04)
   * @description Search for tenants by name, phone, or email within a property.
   *
   * Response follows SDD §3.1 pagination format:
   * ``{"data": [...], "meta": {"page", "limit", "total", "has_next"}}``
   */
  search_tenants_api_v1_tenants_search_get: {
    parameters: {
      query: {
        /** @description Scoping property UUID */
        property_id: string;
        /** @description Search query (min 3 chars) */
        query: string;
        /** @description Field to search: name, phone, or email */
        search_by?: string;
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create a new rental contract
   * @description Creates an active contract for a room+tenant.  Enforces BR-01 (one active per room) and BR-02 (min deposit).
   */
  create_contract_api_v1_contracts_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateContractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ContractCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List active contracts
   * @description Returns all active contracts, optionally filtered by property_id.
   */
  list_active_contracts_api_v1_contracts_active_get: {
    parameters: {
      query?: {
        /** @description Filter by property */
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContractListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get a contract by ID
   * @description Returns full contract details including termination and extensions.
   */
  get_contract_api_v1_contracts__contract_id__get: {
    parameters: {
      path: {
        contract_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContractCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Terminate an active contract
   * @description Terminates an active contract (BR-04).  Requires reason.  Sets room to available.
   */
  terminate_contract_api_v1_contracts__contract_id__terminate_patch: {
    parameters: {
      path: {
        contract_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TerminateContractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContractCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Extend a contract's lease
   * @description Extends the end date of an active contract and records the extension.
   */
  extend_lease_api_v1_contracts__contract_id__extend_post: {
    parameters: {
      path: {
        contract_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExtendLeaseRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ContractCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Renew a terminated/expired contract
   * @description Creates a new contract from a terminated/expired original.  Same room/tenant, updated terms.
   */
  renew_contract_api_v1_contracts__contract_id__renew_post: {
    parameters: {
      path: {
        contract_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RenewContractRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["ContractCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get lease history for a room
   * @description Returns all contracts (past and present) for a given room, newest first.
   */
  get_lease_history_api_v1_leases__room_id__history_get: {
    parameters: {
      path: {
        room_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LeaseHistoryResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Create a maintenance request
   * @description POST /api/v1/maintenance-requests — SDD §3.3.
   */
  create_maintenance_request_api_v1_maintenance_requests_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMaintenanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List pending maintenance requests by property
   * @description GET /api/v1/maintenance-requests/pending — SDD §3.3.
   */
  list_pending_requests_api_v1_maintenance_requests_pending_get: {
    parameters: {
      query: {
        /** @description Filter by property */
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get a maintenance request by ID
   * @description GET /api/v1/maintenance-requests/{id} — SDD §3.3.
   */
  get_maintenance_request_api_v1_maintenance_requests__request_id__get: {
    parameters: {
      path: {
        request_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update maintenance request status
   * @description Updates status per BR-09 workflow: pending → in_progress → resolved/cancelled.
   */
  update_maintenance_status_api_v1_maintenance_requests__request_id__status_patch: {
    parameters: {
      path: {
        request_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMaintenanceStatusRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Assign a maintenance request to a user
   * @description PATCH /api/v1/maintenance-requests/{id}/assign.
   */
  assign_maintenance_request_api_v1_maintenance_requests__request_id__assign_patch: {
    parameters: {
      path: {
        request_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AssignMaintenanceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["MaintenanceCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get dashboard summary
   * @description Returns occupancy, revenue, overdue, and maintenance counts for a property.
   */
  get_dashboard_summary_api_v1_dashboard_summary_get: {
    parameters: {
      query: {
        /** @description Property to query */
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardSummaryWrapper"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get revenue report
   * @description Monthly revenue aggregation for a date range.
   */
  get_revenue_report_api_v1_dashboard_revenue_get: {
    parameters: {
      query: {
        /** @description Property to query */
        property_id: string;
        /** @description Start date (YYYY-MM-DD) */
        start_date?: string | null;
        /** @description End date (YYYY-MM-DD) */
        end_date?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RevenueReportResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get occupancy snapshot
   * @description Returns current occupancy rate and room counts.
   */
  get_occupancy_api_v1_dashboard_occupancy_get: {
    parameters: {
      query: {
        /** @description Property to query */
        property_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["OccupancyResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Send a test notification
   * @description Creates and sends a test notification (mock). Fail-silent — always returns 201.
   */
  send_test_notification_api_v1_notifications_test_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendNotificationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["NotificationCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get notification history
   * @description GET /api/v1/notifications/history.
   */
  get_notification_history_api_v1_notifications_history_get: {
    parameters: {
      query?: {
        /** @description Filter by property */
        property_id?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NotificationListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Resend a failed notification
   * @description PATCH /api/v1/notifications/{id}/resend.
   */
  resend_notification_api_v1_notifications__notif_id__resend_patch: {
    parameters: {
      path: {
        notif_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NotificationCreateResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * View audit logs (paginated)
   * @description Returns paginated audit logs for a property. Owner role required.
   */
  get_audit_logs_api_v1_admin_audit_logs_get: {
    parameters: {
      query: {
        /** @description Filter by property */
        property_id: string;
        /** @description Filter by action type */
        action?: string | null;
        /** @description Page number */
        page?: number;
        /** @description Items per page */
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuditLogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * View system configuration
   * @description Returns system settings with secrets masked. Owner role required.
   */
  get_system_config_api_v1_admin_config_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SystemConfigListResponse"];
        };
      };
    };
  };
}
